In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df= pd.read_csv('mckinsey.csv')

In [5]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [8]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [9]:
df.head(5)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [10]:
df.tail(5)

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [11]:
df.shape

(1704, 6)

In [12]:
## header is not a row

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [14]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [15]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [16]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [17]:
df['country'].nunique()

142

In [18]:
df['continent'].unique()

array(['Asia', 'Europe', 'Africa', 'Americas', 'Oceania'], dtype=object)

In [19]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [20]:
df.continent.nunique()

5

In [21]:
df.continent

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: object

In [22]:
df.continent.value_counts()

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

In [23]:
df.continent.value_counts(normalize = True)

continent
Africa      0.366197
Asia        0.232394
Europe      0.211268
Americas    0.176056
Oceania     0.014085
Name: proportion, dtype: float64

In [24]:
df2= pd.DataFrame(['Male']*8 + ['Gender']*2 , columns=['Gender'])

In [25]:
df2

   Gender
0    Male
1    Male
2    Male
3    Male
4    Male
5    Male
6    Male
7    Male
8  Gender
9  Gender

In [26]:
df2.shape

(10, 1)

In [27]:
df2.nunique()

Gender    2
dtype: int64

In [28]:
df2.value_counts()

Gender
Male      8
Gender    2
Name: count, dtype: int64

In [29]:
df2.value_counts(normalize= True)

Gender
Male      0.8
Gender    0.2
Name: proportion, dtype: float64

In [30]:
df2.value_counts(normalize= True)*100 ## in pervcentage

Gender
Male      80.0
Gender    20.0
Name: proportion, dtype: float64

In [31]:
## renaming of columns

In [32]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [33]:
df.shape

(1704, 6)

In [34]:
df2= df2.rename({'Gender':'gneder'}, axis=1)
df2

   gneder
0    Male
1    Male
2    Male
3    Male
4    Male
5    Male
6    Male
7    Male
8  Gender
9  Gender

In [35]:
df2

   gneder
0    Male
1    Male
2    Male
3    Male
4    Male
5    Male
6    Male
7    Male
8  Gender
9  Gender

In [36]:
df2.rename({'gneder':'gender'}, axis= 1 , inplace=True)

In [37]:
df2

   gender
0    Male
1    Male
2    Male
3    Male
4    Male
5    Male
6    Male
7    Male
8  Gender
9  Gender

In [38]:
df2['dummy_column'] = np.array(np.arange(10), dtype = 'str')

In [39]:
df2

   gender dummy_column
0    Male            0
1    Male            1
2    Male            2
3    Male            3
4    Male            4
5    Male            5
6    Male            6
7    Male            7
8  Gender            8
9  Gender            9

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   gender        10 non-null     object
 1   dummy_column  10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [41]:
df2.head()

  gender dummy_column
0   Male            0
1   Male            1
2   Male            2
3   Male            3
4   Male            4

In [42]:
df2.drop(['dummy_column'] , axis=1 , inplace= True)

In [43]:
df2

   gender
0    Male
1    Male
2    Male
3    Male
4    Male
5    Male
6    Male
7    Male
8  Gender
9  Gender

In [44]:
df2

   gender
0    Male
1    Male
2    Male
3    Male
4    Male
5    Male
6    Male
7    Male
8  Gender
9  Gender

In [45]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [46]:
df3= pd.DataFrame(np.arange(1,21).reshape(5,4))
df3

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

In [47]:
df3.columns = ['a','b','c','d']

In [48]:
df3

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

In [49]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [50]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [51]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [52]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [53]:
for i in range(len(df.columns)):
    print(df.columns[i],':',i)

country : 0
year : 1
population : 2
continent : 3
life_exp : 4
gdp_cap : 5

In [54]:
a= pd.Series(['a','b','c','d','e','f','g','h'], index=[1,2,3,4,5,6,7,8])

In [55]:
a

1    a
2    b
3    c
4    d
5    e
6    f
7    g
8    h
dtype: object

In [56]:
a[4] # using explicit index

'd'

In [57]:
a[:4]

1    a
2    b
3    c
4    d
dtype: object

In [58]:
a[3:7]

4    d
5    e
6    f
7    g
dtype: object

In [59]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [60]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [61]:
df['implicit_index']=np.arange(2,1706)

In [62]:
df

,country,year,population,continent,life_exp,gdp_cap,implicit_index
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,2
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,3
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,4
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,5
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,6
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1701
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1702
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,1703
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,1704
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,1705

In [63]:
df2 =df[['implicit_index','country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap']]

In [64]:
df2

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106
...,...,...,...,...,...,...,...
1699,1701,Zimbabwe,1987,9216418,Africa,62.351,706.157306
1700,1702,Zimbabwe,1992,10704340,Africa,60.377,693.420786
1701,1703,Zimbabwe,1997,11404948,Africa,46.809,792.449960
1702,1704,Zimbabwe,2002,11926563,Africa,39.989,672.038623
1703,1705,Zimbabwe,2007,12311143,Africa,43.487,469.709298

In [65]:
df2[:4]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138

In [66]:
df2.loc[:4]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106

In [67]:
df2.iloc[:4]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138

In [68]:
df2.head(10)

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106
5,7,Afghanistan,1977,14880372,Asia,38.438,786.113360
6,8,Afghanistan,1982,12881816,Asia,39.854,978.011439
7,9,Afghanistan,1987,13867957,Asia,40.822,852.395945
8,10,Afghanistan,1992,16317921,Asia,41.674,649.341395
9,11,Afghanistan,1997,22227415,Asia,41.763,635.341351

In [69]:
df2.loc[:4]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106

In [70]:
df2.iloc[:4]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138

In [71]:
df2.iloc[2:5,1:4]

       country  year  population
2  Afghanistan  1962    10267083
3  Afghanistan  1967    11537966
4  Afghanistan  1972    13079460

In [72]:
df2.loc[:5]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106
5,7,Afghanistan,1977,14880372,Asia,38.438,786.113360

In [73]:
df2[:5]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106

In [74]:
df.iloc[:5]

,country,year,population,continent,life_exp,gdp_cap,implicit_index
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,2
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,3
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,4
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,5
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,6

In [75]:
df.iloc[:5, 0:3]

       country  year  population
0  Afghanistan  1952     8425333
1  Afghanistan  1957     9240934
2  Afghanistan  1962    10267083
3  Afghanistan  1967    11537966
4  Afghanistan  1972    13079460

In [76]:
df2[:5]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106

In [77]:
df2[:5]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106

In [78]:
df

,country,year,population,continent,life_exp,gdp_cap,implicit_index
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,2
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,3
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,4
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,5
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,6
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1701
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1702
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,1703
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,1704
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,1705

In [79]:
df['country'].nunique()

142

In [80]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [81]:
##  how many rows belong tto each conitinent in my dataframe

In [82]:
df['continent']

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: object

In [83]:
df['continent'].value_counts()

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

In [84]:
df['continent'].value_counts(normalize= True)*100

continent
Africa      36.619718
Asia        23.239437
Europe      21.126761
Americas    17.605634
Oceania      1.408451
Name: proportion, dtype: float64

In [85]:
['male']*8 +['Female']*2

['male',
 'male',
 'male',
 'male',
 'male',
 'male',
 'male',
 'male',
 'Female',
 'Female']

In [86]:
tdf3 = pd.DataFrame(['male']*8 +['Female']*2, columns =['Gender'])
tdf3

   Gender
0    male
1    male
2    male
3    male
4    male
5    male
6    male
7    male
8  Female
9  Female

In [87]:
tdf3.value_counts(normalize=True)*100

Gender
male      80.0
Female    20.0
Name: proportion, dtype: float64

In [88]:
tdf3.shape

(10, 1)

In [89]:
tdf3

   Gender
0    male
1    male
2    male
3    male
4    male
5    male
6    male
7    male
8  Female
9  Female

In [90]:
 tdf3

   Gender
0    male
1    male
2    male
3    male
4    male
5    male
6    male
7    male
8  Female
9  Female

In [91]:
tdf3['Gender'].value_counts()

Gender
male      8
Female    2
Name: count, dtype: int64

In [92]:
df

,country,year,population,continent,life_exp,gdp_cap,implicit_index
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,2
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,3
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,4
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,5
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,6
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1701
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1702
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,1703
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,1704
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,1705

In [93]:
df= df.rename({'country':'Country'}, axis = 1)

In [94]:
df

,Country,year,population,continent,life_exp,gdp_cap,implicit_index
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,2
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,3
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,4
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,5
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,6
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1701
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1702
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,1703
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,1704
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,1705

In [95]:
df

,Country,year,population,continent,life_exp,gdp_cap,implicit_index
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,2
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,3
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,4
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,5
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,6
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1701
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1702
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,1703
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,1704
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,1705

In [96]:
df.rename({'Country':'country'} , axis = 1 , inplace = True)

In [97]:
df

,country,year,population,continent,life_exp,gdp_cap,implicit_index
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,2
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,3
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,4
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,5
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,6
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1701
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1702
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,1703
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,1704
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,1705

In [98]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap',
       'implicit_index'],
      dtype='object')

In [99]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [100]:
df.columns[0]

'country'

In [101]:
for i in range(len(df.columns)):
    print(df.columns[i],i)

country 0
year 1
population 2
continent 3
life_exp 4
gdp_cap 5
implicit_index 6

In [102]:
a =pd.Series(['a','b','c','d','e','f','g','h'], index =[1,2,3,4,5,6,7,8])
a

1    a
2    b
3    c
4    d
5    e
6    f
7    g
8    h
dtype: object

In [103]:
a[4] ## uses explicit indexing(if available) ## loc

'd'

In [104]:
a[:4]

1    a
2    b
3    c
4    d
dtype: object

In [105]:
a[3:7] ### slicing uses implicit indexes ### iloc

4    d
5    e
6    f
7    g
dtype: object

In [106]:
df

,country,year,population,continent,life_exp,gdp_cap,implicit_index
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,2
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,3
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,4
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,5
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,6
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1701
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1702
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,1703
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,1704
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,1705

In [107]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap',
       'implicit_index'],
      dtype='object')

In [108]:
df = df[['implicit_index','country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap']]
df

,implicit_index,country,year,population,continent,life_exp,gdp_cap
0,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,6,Afghanistan,1972,13079460,Asia,36.088,739.981106
...,...,...,...,...,...,...,...
1699,1701,Zimbabwe,1987,9216418,Africa,62.351,706.157306
1700,1702,Zimbabwe,1992,10704340,Africa,60.377,693.420786
1701,1703,Zimbabwe,1997,11404948,Africa,46.809,792.449960
1702,1704,Zimbabwe,2002,11926563,Africa,39.989,672.038623
1703,1705,Zimbabwe,2007,12311143,Africa,43.487,469.709298

In [109]:
df.index=np.arange(1,1705)
df

,implicit_index,country,year,population,continent,life_exp,gdp_cap
1,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
2,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
3,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
4,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
5,6,Afghanistan,1972,13079460,Asia,36.088,739.981106
...,...,...,...,...,...,...,...
1700,1701,Zimbabwe,1987,9216418,Africa,62.351,706.157306
1701,1702,Zimbabwe,1992,10704340,Africa,60.377,693.420786
1702,1703,Zimbabwe,1997,11404948,Africa,46.809,792.449960
1703,1704,Zimbabwe,2002,11926563,Africa,39.989,672.038623
1704,1705,Zimbabwe,2007,12311143,Africa,43.487,469.709298

In [110]:
df.head()

,implicit_index,country,year,population,continent,life_exp,gdp_cap
1,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
2,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
3,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
4,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
5,6,Afghanistan,1972,13079460,Asia,36.088,739.981106

In [111]:
df.iloc[0]

implicit_index              2
country           Afghanistan
year                     1952
population            8425333
continent                Asia
life_exp               28.801
gdp_cap            779.445314
Name: 1, dtype: object

In [112]:
df.loc[1]

implicit_index              2
country           Afghanistan
year                     1952
population            8425333
continent                Asia
life_exp               28.801
gdp_cap            779.445314
Name: 1, dtype: object

In [113]:
df.loc[1:3]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
1,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
2,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
3,4,Afghanistan,1962,10267083,Asia,31.997,853.100710

In [114]:
df.iloc[0:4]

,implicit_index,country,year,population,continent,life_exp,gdp_cap
1,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
2,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
3,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
4,5,Afghanistan,1967,11537966,Asia,34.020,836.197138

In [115]:
implicit_index2 = pd.Series(0,)

In [116]:
df.shape

(1704, 7)

In [117]:
implicit_index2

0    0
dtype: int64

In [118]:
df

,implicit_index,country,year,population,continent,life_exp,gdp_cap
1,2,Afghanistan,1952,8425333,Asia,28.801,779.445314
2,3,Afghanistan,1957,9240934,Asia,30.332,820.853030
3,4,Afghanistan,1962,10267083,Asia,31.997,853.100710
4,5,Afghanistan,1967,11537966,Asia,34.020,836.197138
5,6,Afghanistan,1972,13079460,Asia,36.088,739.981106
...,...,...,...,...,...,...,...
1700,1701,Zimbabwe,1987,9216418,Africa,62.351,706.157306
1701,1702,Zimbabwe,1992,10704340,Africa,60.377,693.420786
1702,1703,Zimbabwe,1997,11404948,Africa,46.809,792.449960
1703,1704,Zimbabwe,2002,11926563,Africa,39.989,672.038623
1704,1705,Zimbabwe,2007,12311143,Africa,43.487,469.709298